### ISSUE TITLE
Correction des fautes d'orthographes

### ISSUE THREAD

**Issue by Stivicx** [gregos1810/esx_clip#1]
> RegisterNetEvent('esx_clip:clipcli')
> AddEventHandler('esx_clip:clipcli', function()
>   ped = GetPlayerPed(-1)
>   if IsPedArmed(ped, 4) then
>     hash=GetSelectedPedWeapon(ped)
>     if hash~=nil then
>       TriggerServerEvent('esx_clip:remove')
>       AddAmmoToPed(GetPlayerPed(-1), hash,25)
>       ESX.ShowNotification("tu as utilisé un chargeur")
>     else
>       ESX.ShowNotification("tu n'as pas d'arme en main")
>     end
>   else
>     ESX.ShowNotification("ce type de munition ne convient pas")
>   end
> end)

**Comment by gregos1810** [comment]
fait
